<a href="https://colab.research.google.com/github/AlexsonT/Estatistica_02_Growdev/blob/main/Trabalho_Estat%C3%ADstica_060622.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Imports

In [46]:
import pandas as pd
import numpy as np
from scipy.stats import variation

Baixe o arquivo dados do consumidor 2017 disponível aqui e calcule
algumas medidas descritivas.

In [58]:
df = pd.read_csv('dadosgovbr---2017.csv', sep=';', encoding='latin-1')

pd.set_option('display.max_columns', 38)
df.head()

,Gestor,Canal de Origem,Região,UF,Cidade,Sexo,Faixa Etária,Ano Abertura,Mês Abertura,Data Abertura,Hora Abertura,Data Resposta,Hora Resposta,Data Análise,Hora Análise,Data Recusa,Hora Recusa,Data Finalização,Hora Finalização,Prazo Resposta,Prazo Analise Gestor,Tempo Resposta,Nome Fantasia,Segmento de Mercado,Área,Assunto,Grupo Problema,Problema,Como Comprou Contratou,Procurou Empresa,Respondida,Situação,Avaliação Reclamação,Nota do Consumidor,Análise da Recusa,Edição de Conteúdo,Interação do Gestor,Total
0,Secretaria Nacional do Consumidor,Plataforma Web,N,AM,Manaus,M,entre 31 a 40 anos,2017,1,30/01/2017,14:04:07,09/02/2017,08:36:17,NaN,NaN,NaN,NaN,09/02/2017,11:43:19,09/02/2017,NaN,10.0,Bradesco Promotora,"Bancos, Financeiras e Administradoras de Cartão",Serviços Financeiros,Crédito Consignado (Empréstimo descontado em f...,Cobrança / Contestação,"Cálculo de juros, saldo devedor (contestação, ...",Loja física,S,S,Finalizada avaliada,Não Resolvida,1.0,NaN,N,N,1
1,Departamento de Proteção e Defesa do Consumido...,Plataforma Web,S,RS,Santa Cruz do Sul,F,entre 51 a 60 anos,2017,1,30/01/2017,14:25:22,08/02/2017,16:34:13,NaN,NaN,NaN,NaN,09/02/2017,11:34:58,09/02/2017,NaN,9.0,Pontofrio.com,Comércio Eletrônico,Produtos Eletrodomésticos e Eletrônicos,"Eletroportáteis ( batedeira, liquidificador, u...",Contrato / Oferta,Oferta não cumprida / serviço não fornecido/ v...,Internet,S,S,Finalizada avaliada,Não Resolvida,1.0,NaN,N,N,1
2,Instituto de Defesa do Consumidor - Procon,Plataforma Web,CO,DF,Brasília,F,entre 31 a 40 anos,2017,1,30/01/2017,20:05:01,03/02/2017,11:00:38,NaN,NaN,NaN,NaN,24/02/2017,00:02:27,09/02/2017,NaN,4.0,Samsung,"Fabricantes - Eletroeletrônicos, Produtos de ...",Produtos de Telefonia e Informática,Aparelho celular,Vício de Qualidade,Produto danificado / não funciona - Dificuldad...,Loja física,S,S,Finalizada não avaliada,Não Avaliada,NaN,NaN,N,N,1
3,Instituto Municipal de Proteção e Defesa do Co...,Plataforma Web,SE,RJ,Rio de Janeiro,F,entre 41 a 50 anos,2017,1,30/01/2017,12:41:50,09/02/2017,18:47:52,NaN,NaN,NaN,NaN,11/02/2017,15:56:05,09/02/2017,NaN,10.0,Oi Fixo,"Operadoras de Telecomunicações (Telefonia, Int...",Telecomunicações,Pacote de Serviços ( Combo ),Contrato / Oferta,Oferta não cumprida / serviço não fornecido/ v...,Não comprei / contratei,S,S,Finalizada avaliada,Resolvida,2.0,NaN,N,N,1
4,Departamento de Proteção e Defesa do Consumido...,Plataforma Web,S,RS,Porto Alegre,M,entre 41 a 50 anos,2017,1,30/01/2017,22:13:19,31/01/2017,19:22:55,NaN,NaN,NaN,NaN,21/02/2017,00:01:57,09/02/2017,NaN,1.0,Samsung,"Fabricantes - Eletroeletrônicos, Produtos de ...",Produtos de Telefonia e Informática,Aparelho celular,Contrato / Oferta,Oferta não cumprida / serviço não fornecido/ v...,Loja física,S,S,Finalizada não avaliada,Não Avaliada,NaN,NaN,N,N,1

In [6]:
df.shape

(124563, 38)

1) Apresente as medidas de posição e de tendência central das
variáveis quantitativas.

In [9]:
df.describe()

,Ano Abertura,Mês Abertura,Prazo Analise Gestor,Tempo Resposta,Nota do Consumidor,Total
count,124563.0,124563.000000,11526.000000,114037.000000,70333.000000,124563.0
mean,2017.0,2.406140,4.485424,6.456334,3.331921,1.0
std,0.0,1.100377,3.822539,3.296360,1.695221,0.0
min,2017.0,1.000000,0.000000,0.000000,1.000000,1.0
25%,2017.0,1.000000,1.000000,3.000000,1.000000,1.0
50%,2017.0,2.000000,4.000000,8.000000,4.000000,1.0
75%,2017.0,3.000000,7.000000,9.000000,5.000000,1.0
max,2017.0,4.000000,15.000000,10.000000,5.000000,1.0

In [57]:
# Avalição dos consumidores.

media_nota = df['Nota do Consumidor'].mean()
print(f'A média da avaliação dos consumidores é {media_nota: .2f}.')

mediana_nota = df['Nota do Consumidor'].median()
print(f'A mediana da avaliação do consumidores é {mediana_nota}.')

moda = df['Nota do Consumidor'].mode()[0]
print(f'A moda da avalição dos cosnumidores é {moda}.')

desv_padrao = df['Nota do Consumidor'].std()
print(f'O desvio padrão da avaliação dos consumidores é {desv_padrao: .2f}.')

variancia = df['Nota do Consumidor'].var()
print(f'A variância avaliação dos consumidores é: {variancia: .2f}.')

coef_var = (desv_padrao / media_nota) * 100
print(f'O coeficiente de variação da avaliação dos consumidores é:{coef_var: .2f}%.')

A média da avaliação dos consumidores é  3.30.
A mediana da avaliação do consumidores é 4.0.
A moda da avalição dos cosnumidores é 5.0.
O desvio padrão da avaliação dos consumidores é  1.69.
A variância avaliação dos consumidores é:  2.85.
O coeficiente de variação da avaliação dos consumidores é: 51.21%.

In [75]:
# Resposta dos consumidores.

media_tempo = df['Tempo Resposta'].mean()
print(f'A média do tempo de resposta é de: {media_tempo: .2f}.')

mediana_nota = df['Tempo Resposta'].median()
print(f'A mediana do tempo de resposta é de: {mediana_nota: .2f}.')

moda = df['Tempo Resposta'].mode()[0]
print(f'A moda do tempo de resposta é de: {moda: .2f}.')

desv_padrao = df['Tempo Resposta'].std()
print(f'O desvio padrão do tempo de resposta é de:{desv_padrao: .2f}.')

variancia = df['Tempo Resposta'].var()
print(f'A variância do tempo de resposta é de: {variancia: .2f}.')

coef_var = (desv_padrao / media_nota) * 100
print(f'O coeficiente de variação do tempo de resposta é de :{coef_var: .2f}%.')

A média do tempo de resposta é de:  6.31.
A mediana do tempo de resposta é de:  7.00.
A moda do tempo de resposta é de:  10.00.
O desvio padrão do tempo de resposta é de: 3.40.
A variância do tempo de resposta é de:  11.53.
O coeficiente de variação do tempo de resposta é de : 84.91%.

2) Calcule média e desvio padrão da variável nota por UF.

In [90]:
df2 = df[['Nota do Consumidor', 'UF']]

In [89]:
# Média

df2.groupby('UF').mean()

    Nota do Consumidor
UF
AC            3.465833
AL            3.598789
AM            3.401802
AP            3.501466
BA            3.224435
CE            3.315305
DF            3.314297
ES            3.417162
GO            3.548564
MA            3.293140
MG            3.359397
MS            3.459086
MT            3.366164
PA            3.491699
PB            3.249843
PE            3.311801
PI            3.517701
PR            3.346323
RJ            3.171387
RN            3.297697
RO            3.365169
RR            3.661215
RS            3.578733
SC            3.370197
SE            3.401586
SP            3.167902
TO            3.631270

In [92]:
# Desvio Padrão

df2.groupby('UF').std()

    Nota do Consumidor
UF
AC            1.591323
AL            1.676561
AM            1.633581
AP            1.688411
BA            1.684812
CE            1.690886
DF            1.657951
ES            1.657420
GO            1.639947
MA            1.705108
MG            1.691930
MS            1.633667
MT            1.642110
PA            1.645376
PB            1.727524
PE            1.696566
PI            1.639264
PR            1.675320
RJ            1.712231
RN            1.700010
RO            1.677359
RR            1.510212
RS            1.643977
SC            1.666343
SE            1.683319
SP            1.697923
TO            1.663180

3) Calcule a média e o desvio padrão para a variável Tempo Resposta por mês de abertura.

In [93]:
df3 = df[['Tempo Resposta', 'Mês Abertura']]

In [94]:
# Média

df3.groupby('Mês Abertura').mean()

              Tempo Resposta
Mês Abertura
1                   6.145255
2                   6.788504
3                   6.466894
4                   6.454246
5                   6.138679
6                   5.735571
7                   5.917671
8                   6.166328
9                   6.511480
10                  6.479321
11                  6.420560
12                  6.742453

In [96]:
# Desvio Padrão

df3.groupby('Mês Abertura').std()

              Tempo Resposta
Mês Abertura
1                   3.502052
2                   3.093170
3                   3.355131
4                   3.177384
5                   3.411408
6                   3.556943
7                   3.496550
8                   3.285124
9                   3.149630
10                  3.296008
11                  3.413333
12                  3.716309

4) Proporção de reclamações registradas e não respondidas.

In [142]:
df4 = df[['Respondida']]

df4['Respondida'].value_counts(dropna = False, normalize = True)

S    0.914631
N    0.085369
Name: Respondida, dtype: float64

In [151]:
nao = df4.loc[df4['Respondida'] == "N"].count()

total = df4['Respondida'].count()

proporcao = float((nao / total) * 100)

print(f' As reclamações não respondidas representam o total de {proporcao: .2f}% do total.')

 As reclamações não respondidas representam o total de  8.54% do total.